import type { ReactNode } from "react";
import {
  Info,
  Layers,
  CloudSun,
  Satellite,
  Sprout,
  Droplets,
  Lightbulb,
  AlertTriangle,
  HelpCircle,
  FileText,
  type LucideIcon,
} from "lucide-react";
import { getCropVisual, scoreTone } from "@/lib/cropVisual";

/**
 * Structured, card-based rendering of the markdown generated by
 * `agent_agriculture` (stage 2 of the LLM pipeline, see
 * `backend/agent_agriculture/app/services/synthesis_service.py`).
 *
 * The synthesis prompt is deliberately constrained to an EXACT, predictable
 * structure - `## <section>` headings in a fixed order, with `### N. <crop>`
 * sub-headings inside "Cultures recommandées" each starting with
 * `**Score : NN%**` - so instead of dumping a long scrolling wall of
 * markdown text (which reads like a newsletter), each top-level section
 * becomes its own icon-labeled card, and crop entries become compact score
 * cards. Unknown/renamed headings still render (generic icon + text), so a
 * slightly different LLM output never breaks the page.
 */
export function ReportMarkdown({ markdown }: { markdown: string }) {
  const sections = splitSections(markdown);
  return (
    <div className="space-y-4">
      {sections.map((section, i) =>
        section.title ? <ReportSection key={i} section={section} /> : <div key={i}>{renderBody(section.lines)}</div>,
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

type Section = { title: string; lines: string[] };

function splitSections(markdown: string): Section[] {
  const sections: Section[] = [];
  let current: Section | null = null;
  for (const raw of markdown.split("\n")) {
    const line = raw.trimEnd();
    if (line.startsWith("## ")) {
      if (current) sections.push(current);
      current = { title: line.slice(3).trim(), lines: [] };
    } else if (current) {
      current.lines.push(line);
    } else if (line.trim() !== "") {
      current = { title: "", lines: [line] };
    }
  }
  if (current) sections.push(current);
  return sections;
}

type CropBlock = { rank: string; name: string; score: number | null; description: string };

function parseCropBlocks(lines: string[]): CropBlock[] {
  const blocks: { rank: string; name: string; bodyLines: string[] }[] = [];
  let current: { rank: string; name: string; bodyLines: string[] } | null = null;
  for (const raw of lines) {
    const line = raw.trim();
    const heading = line.match(/^###\s+(\d+)\.\s*(.+)$/);
    if (heading) {
      if (current) blocks.push(current);
      current = { rank: heading[1], name: heading[2].trim(), bodyLines: [] };
    } else if (current && line !== "") {
      current.bodyLines.push(line);
    }
  }
  if (current) blocks.push(current);

  return blocks.map(({ rank, name, bodyLines }) => {
    const scoreLine = bodyLines.find((l) => /score\s*:/i.test(l));
    const scoreMatch = scoreLine?.match(/(\d+(?:[.,]\d+)?)\s*%/);
    const score = scoreMatch ? parseFloat(scoreMatch[1].replace(",", ".")) : null;
    const description = bodyLines
      .filter((l) => l !== scoreLine)
      .join(" ")
      .replace(/\*\*/g, "")
      .trim();
    return { rank, name, score, description };
  });
}

// ---------------------------------------------------------------------------
// Section visuals
// ---------------------------------------------------------------------------

type SectionVisual = { icon: LucideIcon; bg: string; fg: string; tint?: "warning" | "muted" };

function normalize(title: string): string {
  return title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

const SECTION_VISUALS: Record<string, SectionVisual> = {
  "resume de la parcelle": { icon: Info, bg: "oklch(0.92 0.05 230)", fg: "oklch(0.5 0.09 230)" },
  sol: { icon: Layers, bg: "oklch(0.92 0.05 60)", fg: "oklch(0.5 0.09 60)" },
  meteo: { icon: CloudSun, bg: "oklch(0.92 0.05 230)", fg: "oklch(0.55 0.09 230)" },
  vegetation: { icon: Satellite, bg: "oklch(0.92 0.05 150)", fg: "oklch(0.45 0.1 150)" },
  "cultures recommandees": { icon: Sprout, bg: "oklch(0.92 0.05 145)", fg: "oklch(0.45 0.12 145)" },
  "fertilisation et irrigation": { icon: Droplets, bg: "oklch(0.92 0.05 230)", fg: "oklch(0.5 0.1 230)" },
  "conseils pratiques": { icon: Lightbulb, bg: "oklch(0.93 0.08 85)", fg: "oklch(0.55 0.13 75)" },
  alertes: { icon: AlertTriangle, bg: "oklch(0.92 0.07 30)", fg: "oklch(0.5 0.14 25)", tint: "warning" },
  "donnees manquantes": { icon: HelpCircle, bg: "oklch(0.93 0.01 90)", fg: "oklch(0.52 0.01 90)", tint: "muted" },
};
const DEFAULT_SECTION_VISUAL: SectionVisual = { icon: FileText, bg: "oklch(0.93 0.01 90)", fg: "oklch(0.5 0.01 90)" };

function sectionVisual(title: string): SectionVisual {
  return SECTION_VISUALS[normalize(title)] ?? DEFAULT_SECTION_VISUAL;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function ReportSection({ section }: { section: Section }) {
  const { icon: Icon, bg, fg, tint } = sectionVisual(section.title);
  const isCrops = normalize(section.title) === "cultures recommandees";
  const cropBlocks = isCrops ? parseCropBlocks(section.lines) : [];

  return (
    <div
      className={
        "rounded-2xl border p-5 " +
        (tint === "warning"
          ? "border-waste/30 bg-waste/5"
          : tint === "muted"
            ? "border-border bg-secondary/30"
            : "border-border bg-card")
      }
    >
      <div className="flex items-center gap-3 mb-3">
        <div className="h-9 w-9 rounded-xl flex items-center justify-center shrink-0" style={{ background: bg, color: fg }}>
          <Icon className="h-4 w-4" />
        </div>
        <h3 className="font-display text-lg font-semibold">{section.title}</h3>
      </div>
      {isCrops && cropBlocks.length > 0 ? (
        <div className="space-y-2.5">
          {cropBlocks.map((block) => (
            <CropReportCard key={block.rank} block={block} />
          ))}
        </div>
      ) : (
        renderBody(section.lines)
      )}
    </div>
  );
}

function CropReportCard({ block }: { block: CropBlock }) {
  const { icon: Icon, bg, fg } = getCropVisual(block.name);
  const tone = block.score !== null ? scoreTone(block.score) : { bg: "oklch(0.93 0.01 90)", fg: "oklch(0.5 0.01 90)" };
  return (
    <div className="rounded-2xl bg-secondary/40 p-4 flex items-start gap-3">
      <div className="h-10 w-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: bg, color: fg }}>
        <Icon className="h-5 w-5" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex items-center justify-between gap-2 flex-wrap">
          <div className="font-semibold">
            {block.rank}. {block.name}
          </div>
          {block.score !== null && (
            <span
              className="shrink-0 rounded-full px-2.5 py-0.5 text-xs font-bold"
              style={{ background: tone.bg, color: tone.fg }}
            >
              Score : {block.score}%
            </span>
          )}
        </div>
        {block.description && <p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">{block.description}</p>}
      </div>
    </div>
  );
}

function renderBody(lines: string[]): ReactNode[] {
  const blocks: ReactNode[] = [];
  let listBuffer: string[] = [];
  let key = 0;

  function flushList() {
    if (listBuffer.length === 0) return;
    blocks.push(
      <ul key={`ul-${key++}`} className="list-disc pl-5 space-y-1.5 my-1 text-sm leading-relaxed">
        {listBuffer.map((item, i) => (
          <li key={i}>{renderInline(item)}</li>
        ))}
      </ul>,
    );
    listBuffer = [];
  }

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith("### ")) {
      flushList();
      blocks.push(
        <h4 key={key++} className="font-semibold text-sm mt-3 mb-1">
          {line.slice(4)}
        </h4>,
      );
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      listBuffer.push(line.slice(2));
    } else if (line.trim() === "") {
      flushList();
    } else {
      flushList();
      blocks.push(
        <p key={key++} className="text-sm leading-relaxed my-1 text-foreground/90">
          {renderInline(line)}
        </p>,
      );
    }
  }
  flushList();
  return blocks;
}

function renderInline(text: string): ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={i}>{part.slice(2, -2)}</strong>;
    if (part.startsWith("*") && part.endsWith("*")) return <em key={i}>{part.slice(1, -1)}</em>;
    return <span key={i}>{part}</span>;
  });
}
