/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgricultureRouteImport } from './routes/agriculture'
import { Route as AujourdHuiRouteImport } from './routes/aujourd-hui'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RegulationRouteImport } from './routes/regulation'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as MarketplaceMesAnnoncesRouteImport } from './routes/marketplace.mes-annonces'
import { Route as MarketplaceNouveauRouteImport } from './routes/marketplace.nouveau'
import { Route as OnboardingTerrainRouteImport } from './routes/onboarding.terrain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultureRoute = AgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const AujourdHuiRoute = AujourdHuiRouteImport.update({
  id: '/aujourd-hui',
  path: '/aujourd-hui',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationRoute = RegulationRouteImport.update({
  id: '/regulation',
  path: '/regulation',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceMesAnnoncesRoute = MarketplaceMesAnnoncesRouteImport.update({
  id: '/mes-annonces',
  path: '/mes-annonces',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceNouveauRoute = MarketplaceNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => MarketplaceRoute,
} as any)
const OnboardingTerrainRoute = OnboardingTerrainRouteImport.update({
  id: '/onboarding/terrain',
  path: '/onboarding/terrain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aujourd-hui': typeof AujourdHuiRoute
  '/business': typeof BusinessRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/profil': typeof ProfilRoute
  '/regulation': typeof RegulationRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/mes-annonces': typeof MarketplaceMesAnnoncesRoute
  '/marketplace/nouveau': typeof MarketplaceNouveauRoute
  '/onboarding/terrain': typeof OnboardingTerrainRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aujourd-hui': typeof AujourdHuiRoute
  '/business': typeof BusinessRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/profil': typeof ProfilRoute
  '/regulation': typeof RegulationRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/mes-annonces': typeof MarketplaceMesAnnoncesRoute
  '/marketplace/nouveau': typeof MarketplaceNouveauRoute
  '/onboarding/terrain': typeof OnboardingTerrainRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aujourd-hui': typeof AujourdHuiRoute
  '/business': typeof BusinessRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/profil': typeof ProfilRoute
  '/regulation': typeof RegulationRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/mes-annonces': typeof MarketplaceMesAnnoncesRoute
  '/marketplace/nouveau': typeof MarketplaceNouveauRoute
  '/onboarding/terrain': typeof OnboardingTerrainRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agriculture'
    | '/aujourd-hui'
    | '/business'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/marketplace'
    | '/profil'
    | '/regulation'
    | '/marketplace/$id'
    | '/marketplace/mes-annonces'
    | '/marketplace/nouveau'
    | '/onboarding/terrain'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agriculture'
    | '/aujourd-hui'
    | '/business'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/profil'
    | '/regulation'
    | '/marketplace/$id'
    | '/marketplace/mes-annonces'
    | '/marketplace/nouveau'
    | '/onboarding/terrain'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/agriculture'
    | '/aujourd-hui'
    | '/business'
    | '/connexion'
    | '/dashboard'
    | '/inscription'
    | '/marketplace'
    | '/profil'
    | '/regulation'
    | '/marketplace/$id'
    | '/marketplace/mes-annonces'
    | '/marketplace/nouveau'
    | '/onboarding/terrain'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgricultureRoute: typeof AgricultureRoute
  AujourdHuiRoute: typeof AujourdHuiRoute
  BusinessRoute: typeof BusinessRoute
  ConnexionRoute: typeof ConnexionRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  RegulationRoute: typeof RegulationRoute
  OnboardingTerrainRoute: typeof OnboardingTerrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriculture': {
      id: '/agriculture'
      path: '/agriculture'
      fullPath: '/agriculture'
      preLoaderRoute: typeof AgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aujourd-hui': {
      id: '/aujourd-hui'
      path: '/aujourd-hui'
      fullPath: '/aujourd-hui'
      preLoaderRoute: typeof AujourdHuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulation': {
      id: '/regulation'
      path: '/regulation'
      fullPath: '/regulation'
      preLoaderRoute: typeof RegulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/mes-annonces': {
      id: '/marketplace/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/marketplace/mes-annonces'
      preLoaderRoute: typeof MarketplaceMesAnnoncesRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/nouveau': {
      id: '/marketplace/nouveau'
      path: '/nouveau'
      fullPath: '/marketplace/nouveau'
      preLoaderRoute: typeof MarketplaceNouveauRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/onboarding/terrain': {
      id: '/onboarding/terrain'
      path: '/onboarding/terrain'
      fullPath: '/onboarding/terrain'
      preLoaderRoute: typeof OnboardingTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceMesAnnoncesRoute: typeof MarketplaceMesAnnoncesRoute
  MarketplaceNouveauRoute: typeof MarketplaceNouveauRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceMesAnnoncesRoute: MarketplaceMesAnnoncesRoute,
  MarketplaceNouveauRoute: MarketplaceNouveauRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgricultureRoute: AgricultureRoute,
  AujourdHuiRoute: AujourdHuiRoute,
  BusinessRoute: BusinessRoute,
  ConnexionRoute: ConnexionRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ProfilRoute: ProfilRoute,
  RegulationRoute: RegulationRoute,
  OnboardingTerrainRoute: OnboardingTerrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
